_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#100'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#200'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#300'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#500'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#600'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#800'
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#900'
load_on_themes:
  ap_dxpr: ap_dxpr
