_core:
  default_config_hash: OhypfKr4_Eo8XwXg3Sios05lN-LjxOhSdSOSkEN9Ndo
logo:
  use_default: false
  path: 'sites/default/files/Alpine Pickup_Alpine Pickup Dark Green Transparent_0.png'
brand_image:
  use_default: true
