_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: mail.alpinepickup.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: info@alpinepickup.com
smtp_password: 'Drup@ld3v#'
smtp_from: info@alpinepickup.com
smtp_fromname: 'Alpine Pickup'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: info@deepsearchrecords.com
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
