commerce_payment.commerce_payment_gateway.plugin.paypal_express_checkout_subscription:
  type: commerce_payment_gateway_configuration
  mapping:
    api_username:
      type: string
      label: 'API Username'
    api_password:
      type: string
      label: 'API Password'
    shipping_prompt:
      type: string
      label: 'Shipping address collection'
    signature:
      type: string
      label: 'Signature'
    solution_type:
      type: string
      label: 'Type of checkout flow'
    billing_period:
      type: select
      label: 'Select Billing Period'
